# Generated by Django 3.1.1 on 2020-09-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_auto_20200909_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=16, null=True, unique=True)),
                ('movie', models.ManyToManyField(to='auth_module.Movie')),
            ],
        ),
    ]
