# Generated by Django 3.1.1 on 2020-09-09 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_auto_20200909_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='movie',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), default=list, size=None),
        ),
    ]
